### ISSUE TITLE
Ajustes en el diseño de pantalla

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#2]
- [x] Revisar botones
- [x] Revisar pantallas que estén faltando

**Comment by GabiPezet** [comment]
1. Se revisaron las pantallas faltantes
2. Se inserta una TopBar a la HomeScreen que incluye un more vertical con menú desplegable
3. Se inserta en el menú desplegable del more vertical una pantalla de Registro Múltiple.
4. Se desplegó el menú de selección en 3 pantallas independientes:

- Pantalla de selección de personaje del usuario
- Pantalla de selección de personaje para la COM
- Pantalla de selección del escenario de combate

5. La pantalla de combate se mantiene igual para el modo de juego Arcade original
6. Se agrega al menú desplegable del more vertical una opción de acceso a perfil.

**Comment by GabiPezet** [comment]
Se revisaron las pantallas faltantes
    Se inserta una TopBar a la HomeScreen que incluye un more vertical con menú desplegable
    Se inserta en el menú desplegable del more vertical una pantalla de Registro Múltiple.
    Se desplegó el menú de selección en 3 pantallas independientes:

    Pantalla de selección de personaje del usuario
    Pantalla de selección de personaje para la COM
    Pantalla de selección del escenario de combate

    La pantalla de combate se mantiene igual para el modo de juego Arcade original
    Se agrega al menú desplegable del more vertical una opción de acceso a perfil.
