### ISSUE TITLE
Pantalla Selección de Personajes

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#3]
- [x] #4 
- [x] #5 
- [x] Lista de componete ItemPersonajes

**Comment by GabiPezet** [comment]
1. Se mejora la performance, la visión y la estética de la pantalla de selección de personaje
2. Se realizaron varias pruebas previas a la versión final de la pantalla de selección de personaje, pasando por LazyHorizontalGrid/LazyVerticalGrid/LazyColumn. Se termina optando por una LazyRow, Card del personaje ocupa el BW de la pantalla para mejor visión de la selección del personaje.
3. Se implementa la llamada a la API para traer la lista de personajes.
4. 
![SelectPlayerScreen_scheme](https://github.com/user-attachments/assets/cb566994-d0a1-4a79-a3ba-6f5f9bb2f75e)
