### ISSUE TITLE
Componente Item Personaje

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#4]
https://www.figma.com/design/0rYTusDxTYTRVht2BKANdc/Untitled?node-id=7-1118&t=t5QlSyu9R56OYU0N-4

```kotlin

data class SuperHeroCombat(
    val id: String,
    val name: String,
    val image: SuperHeroImage,
    val damageAbsMax: Int,
    var attack: Int,
    var defense: Int,
    var life: Int,
    var damageAbs: Int,
    var damagePenance: Int,
    var healingPotion: Int
)

@Composable
fun CharacterItem(character: SuperHeroCombat) {
}


```

**Comment by GabiPezet** [comment]
1. Implementada la lógica de combate inicial ÚNICAMENTE para el modo Arcade original del FutureFight 1.0

![imagen](https://github.com/user-attachments/assets/b663e751-a505-4392-90cc-406915d57b4c)

2. Se toma desde la API los siguientes atributos:
![imagen](https://github.com/user-attachments/assets/3b546fa7-ad4d-4605-a42d-8eeb121f72cd)

3. Aún no se definen mejoras para la visualización de los PowerStats de los Héroes:

![PowerStats_MapOfHero](https://github.com/user-attachments/assets/b1048d7f-64a8-4ea5-95d1-d2073ad5a033)
