### ISSUE TITLE
Primary Button

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#5]
Definir y construir el composable del botón principal de acción

**Comment by GabiPezet** [comment]
1. Redefinido y construido el composable del botón principal de acción, El mismo se utiliza en las siguientes pantallas:

- HomeScreen para iniciar la experiencia del usuario 
- SelectPlayerScreen para seleccionar el personaje principal del Usuario
- SelectComScreen para seleccionar el antagonista del combate en el modo Arcade tradicional
- SelectMapScreen para seleccionar el escenario de combate.

![Botón Composable (1)](https://github.com/user-attachments/assets/62ed2ff4-9e18-4a58-abce-fbe6bcb61de0)
![Botón Composable (2)](https://github.com/user-attachments/assets/a2e3622e-fe58-4c5d-8e55-929ce0c0aff0)
![Botón Composable (3)](https://github.com/user-attachments/assets/36cece97-0658-4ad9-bc83-3c91b1e9b2f0)
