### ISSUE TITLE
SuperHeroCombat Repository

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#6]
Obtener el listado de los super héroes que se pueden elegir.

**Comment by GabiPezet** [comment]
1. Finalizada la llamada a la API que trae la lista de superHeroes seleccionables:

![imagen](https://github.com/user-attachments/assets/c81869c9-3626-44b5-9f20-683de8fbda7d)

2. Se comienza a implementar Patrón Repository con la dependencia de las correspondientes interfaces.

![imagen](https://github.com/user-attachments/assets/a919fee1-0e65-4214-ab0d-4cd4e39e9898)
