### ISSUE TITLE
Pantalla selección de mapa

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#7]
- [x] #8 
- [x] #5 
- [x] MapItemList

https://www.figma.com/design/0rYTusDxTYTRVht2BKANdc/Untitled?node-id=7-1506&t=t5QlSyu9R56OYU0N-4

**Comment by GabiPezet** [comment]
1. Se finaliza el esquema de la pantalla de selección de mapa,
2. Se agrega el Composable del botón de acción del usuario.
3. Se define que la pantalla de SelectMapScreen es la última antes del Modo combate Arcade original.

![SelectMapScreen_scheme](https://github.com/user-attachments/assets/9c9e3962-3051-4c60-9a9d-ec83ccb20680)
