### ISSUE TITLE
MapItem

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#8]
- [ ] Composable

```kotlin
@Composable
fun MapItem(map: Map) {
// ...
}

```

https://www.figma.com/design/0rYTusDxTYTRVht2BKANdc/Untitled?node-id=7-1506&t=t5QlSyu9R56OYU0N-4

**Comment by GabiPezet** [comment]
Los mapas BackGround de combate se insertan en el repositorio de manera local en el  CombatBackgroundData

se crea una ListOf ( ) con los mapas seleccionables por el usuario.

en el futuro se re-diseñarán los mapas para que se ajusten al diseño y los requerimientos estéticos de FF Evolution.

esto irá en consonancia con todo lo que es Logo, imágenes e Iconos dentro de la app.
