### ISSUE TITLE
Maps Repository

### ISSUE THREAD

**Issue by Thargelion** [unlam-tec-movil/A3-2024-h2-E4#9]
Un Repositorio con todos los mapas disponibles.

**Comment by GabiPezet** [comment]
1. Se crea repositorio con todos los mapas disponibles (momentáneamente) 
2. Eventualmente se planifica el diseño de nuevos mapas que coincidan con la estética y el diseño de FF Evolution.
3. El repositorio se mantiene lleno con los mapas clásicos pero solo hasta diseñar las nuevas arenas.
![imagen](https://github.com/user-attachments/assets/07daa60b-1b15-460f-b568-3dbbdb2b00c2)
